### ISSUE TITLE
question

### ISSUE THREAD

**Issue by eduarddrenth** [BCDH/cql-module#1]
This module turns a cql string into an xml equivalent, does it also enable searching material in existdb using cql?

**Comment by adamretter** [comment]
The module itself just returns the XML representation of CQL.

My colleague @rg-coder wrote some XQuery which transforms that XML into some XQuery expressions and a different XML vocabulary which is used with the `ft:query` full-text search function in eXist to do a structured full-text search.

The XQuery code was created for @ttasovac at @BCDH and is not yet public. I am not sure if @ttasovac's plans to open this up or not. Perhaps he could comment?

**Comment by adamretter** [comment]
@eduarddrenth btw I was initially inspired by the BlackLab CQL Parser, but found it impossible to reuse in my own code. I tried to write this code so that the (Antlr) parser could easily be reused.

**Comment by eduarddrenth** [comment]
I understand that...there is also this:
https://github.com/meertensinstituut/mtas/blob/master/src/mtas/parser/cql/MtasCQLParser.jj
don't know if it is better / more reusable.

And...the xquery needed very much depends on how the encoding is done in
xml, perhaps when this: https://github.com/LingSIG/wordAttributes /
finalizes it is more useful to translate to xquery.

Or perhaps use some form of configuration/mapping to support different
encodings. Or simply don't support cql, everything it can do is probably
possible in xquery, although I doubt it will be easy to support the
positioning features of cql.

**Comment by ttasovac** [comment]
Hi @eduarddrenth. Еventually, we'll make the code that we use to construct CQL queries available, but it's part of a larger project and for various organizational reasons that will have to wait a bit.

@rg-coder, I wonder if you could paste here a couple of examples from the Izdanak API where we use the CQL module?

**Comment by rg-coder** [comment]
Using the CQL Module and the API, user could search the paragraphs in existdb having lemma="see" using query , '[lemma="see"]'  in their application and highlights the matched words as shown in the following XML:

```xml
<p xml:id="test">
    <s xml:id="P13.t1.p2.s2">
       <w xml:id="P13.t1.p2.w1">He</w>
       <w xml:id="P13.t1.p2.w2" lemma="see">saw</w>
       <w xml:id="P13.t1.p2.w3">the</w>
       <w xml:id="P13.t1.p2.w4">birds</w>
       <w xml:id="P13.t1.p2.w5">chirping</w>!
    </s>
</p>
````

CQL module written explicitly will turn the query '[lemma="see"]' to following XML:

```xml
<cql:query xmlns:cql="http://humanistika.org/ns/exist/module/cql">
    <cql:position>
       <cql:attribute name="lemma">see</cql:attribute>
   </cql:position>
</cql:query>
```

Then API does the transformation this XML to XQuery through the API written and run the results:
```xml
"//p[ft:query(.//w/@lemma,<query><term>see</term></query>)]"
```

Ultimately it will render the results on browser as:

`He` **saw** `the birds chirping!`

If you want some more examples @eduarddrenth , please let me know.

**Comment by eduarddrenth** [comment]
ok, looks like an option if we want to support CQL.

At the moment I am having a hard time getting our tei corpora published
with TEI publisher.

After that I want to create an app to query the material using stadard
options.

Finaly we may want to support CQL. So it will take a while before we come
to that.

Thanks, Eduard
