### ISSUE TITLE
module namespace url is returning 523 Origin is unreachable 

### ISSUE THREAD

**Issue by marmoure** [BCDH/cql-module#2]
I was trying the demo from the readme and i was getting an IO error in exide
i tried reaching out to the module namespace url and i was getting `Origin is unreachable Error code 523`

https://humanistika.org/ns/exist/module/cql

**Comment by ttasovac** [comment]
hm... that website has been down for a while now... i should try to get it up and running or at least avoid the error code for the particular URI. sorry about this. i will look into it next week.
